package polyhook

import "github.com/untrustedmodders/go-plugify"

// Generated from polyhook

// HookHandle - Handle generated by Hook functions
type HookHandle = uintptr

// ParametersHandle - Represent array of function parameters
type ParametersHandle = uintptr

// ReturnHandle - Represent object of function return
type ReturnHandle = uintptr

// RegistersHandle - Represent array of registers
type RegistersHandle = uintptr


